### ISSUE TITLE
Prevented other extensions from running

### ISSUE THREAD

**Issue by doncid** [nvuillam/vscode-groovy-lint#100]
[NicolasVuillamy.vscode-groovy-lint-unresponsive.cpuprofile.txt](https://github.com/nvuillam/vscode-groovy-lint/files/5883455/NicolasVuillamy.vscode-groovy-lint-unresponsive.cpuprofile.txt)

**Comment by nvuillam** [comment]
Could you detail how to reproduce the problem and what are the other extensions installed on your VsCode ?
