### ISSUE TITLE
Need maintainers :)

### ISSUE THREAD

**Issue by nvuillam** [nvuillam/vscode-groovy-lint#105]
I've got less and less available time to maintain vscode-groovy-lint (new job as CTO + [Mega-Linter](https://github.com/nvuillam/mega-linter/) project)

I also do not use groovy anymore in my daily work, so maintaining vscode-groovy-lint has become a low priority :/

I will continue do to as much as I can but it may not be enough to keep vscode-groovy-lint at its best quality.... 

So anyone would like to **join vscode-groovy-lint project** ? :)

I will of course provide all required support :)

**Comment by shadycuz** [comment]
I see no one stepped up. ☹️ 

This project is to important to the Groovy/Jenkins ecosystem and I see the CI builds are starting to fail. I'm the maintainer of the [jenkins-extension-pack](https://marketplace.visualstudio.com/items?itemName=DontShaveTheYak.jenkins-extension-pack) and [groovy-guru](https://marketplace.visualstudio.com/items?itemName=DontShaveTheYak.groovy-guru) vscode extentions.

I can help keep the CICD pipelines working, getting PR's merged from contributors and getting releases out to vscode. I can also automate them completely if they are not already. I'm not sure I can contribute any features at first, but it's likely I could fix things if they did break.

**Comment by nvuillam** [comment]
@shadycuz that's nice from you to propose your help :)

About VsCode Groovy Lint, the next step would be to upgrade to npm-groovy-lint@9.0.0 (based on CodeNarc 2.2, that I built recently)

Currently it is using previous version of npm-groovy-lint, so based on CodeNarc 2.0

Would you like to try to perform the upgrade ?

I think that most of the complexity is about test cases, and I can of course provide support :)

**Comment by nvuillam** [comment]
@stevenh saved the day ^^

But any new contributors are always welcomed :)
