### ISSUE TITLE
Weird interaction with Prettier code formatter ?

### ISSUE THREAD

**Issue by markhowells** [nvuillam/vscode-groovy-lint#110]
I've installed groovy-lint to format a Jenkinsfile in a JS project

The linter works except for formatting when hitting "Shift Alt F" invokes Prettier rather than groovy-lint.

Is there a setting in vscode I need to set to bind groovy-lint to groovy files? I have groovy-lint enabled as a formatted...

**Comment by nvuillam** [comment]
I think that if you disable Prettier for Groovy, it should be ok :)

https://stackoverflow.com/a/54469658/7113625

**Comment by felipecrs** [comment]
I do something different:

```
"[groovy]": {
  "editor.defaultFormatter": "NicolasVuillamy.vscode-groovy-lint",
},
```
