### ISSUE TITLE
Run same linting locally as in CICD

### ISSUE THREAD

**Issue by shadycuz** [nvuillam/vscode-groovy-lint#122]
Currently the `npm lint` runs `eslint`, while CICD the `megalinter` is run. 

We should either change `npm lint` to run `megalinter` via the `mega-linter-runner` command, or we could add a `npm run megalinter` script to run  the `mega-linter-runner` command.

Either way we will need to add  `mega-linter-runner`  to the dev dependencies for this project. 

This would be a good first issue for someone new to vscode-groovy-lint but would like to contribute.

**Comment by nvuillam** [comment]
mega-linter-runner is docker-image based, so wayyy to heavy for a local linting in my opinion
As Mega-Linter uses the same eslint config, the result should be the same ^^

**Comment by shadycuz** [comment]
I'm not worried about linting the code, I was worried about all the other failures in CI, like the dead links in README. I think most contributors are not going to want to push and wait and see if it passes. 

Maybe we can change the CI so that on feature branches we only lint the code, and on `develop` we run the full mega linter?
