### ISSUE TITLE
Create a develop branch so every PR isn't a release

### ISSUE THREAD

**Issue by shadycuz** [nvuillam/vscode-groovy-lint#123]
This project could really benefit from having a `develop` branch to merge feature branches into. Currently every PR is treated as a "Release". Instead we could merge several small PR's into `develop`, like all the `dependabot` PR's. We could then setup automation to generate what the changelog would look like, create a `draft` or `pre-release` in github releases, and of course re-run the test suite with all the combined changes. We could even create the vscode `vsix` extension file so the changes in `develop` branch are easy to test. Kinda like our own `vscode-groovy-lint insiders` program. All of these things except changelog generation are already in place in the the [Groovy-Guru](https://github.com/DontShaveTheYak/groovy-guru) extension.

Then when ever you want to make a new release you just merge develop into master/main. This is a stepping stone to completely automated releases because you can just put the type of change as a label on the PR and let the automation figure out the version number. See this Groovy-Guru [PR](https://github.com/DontShaveTheYak/groovy-guru/pull/23).

**Comment by nvuillam** [comment]
I'm used to have released reated by "new release" action on github repo, i'll try to do that someday, exactly like with https://github.com/hardisgroupcom/vscode-sfdx-hardis/blob/master/.github/workflows/deploy-RELEASE.yml

**Comment by nvuillam** [comment]
Done, now merge in master do nothing, and creating a release publishes a new version of the vscode extension :)
