### ISSUE TITLE
Be able to use a global .groovylinter.json file

### ISSUE THREAD

**Issue by redsigma** [nvuillam/vscode-groovy-lint#126]
Is there a way to have a default `.groovylinter.json` file besides the project-level file. I tried to use `groovyLint.basic.config` with an absolute path to a custom json but it doesnt use the file, so i am not sure what that option does because the description is pretty much not clear.

Maybe a solution could be to have an option such as `groovyLinter.linter.args` which appends arguments to the npm linter executable

**Comment by nvuillam** [comment]
it seems that `groovyLint.basic.config` is the right setting to define... but it seems to be used nowhere :o 

npm-groovy-lint is called as a library, not CLI, so can not manage linter.args, but... with a PR taking in account `groovyLint.basic.config` it should be ok :)

**Comment by nvuillam** [comment]
@redsigma please can you try again with latest version ? :) (you may need to define the folder containing your global .groovylintrc.json file)

**Comment by redsigma** [comment]
> @redsigma please can you try again with latest version ? :) (you may need to define the folder containing your global .groovylintrc.json file)

I checked the latest version and now it succesfully detects  $HOME/.groovylintrc.json  . However i tried to set `groovyLint.basic.config` to ` $HOME/.config/vscode/.groovylintrc.json` but unfortunately it was not used.

Currently i am using the `$HOME/.groovylintrc.json` file,

**Comment by nvuillam** [comment]
Not sure npm-groovy-lint does env var replacements, what if you define the exact path without $HOME ?

**Comment by redsigma** [comment]
> Not sure npm-groovy-lint does env var replacements, what if you define the exact path without $HOME ?

I have tried with the exact absolute path but it still did not work

**Comment by nvuillam** [comment]
I made a little update
Please can you install latest version and screenshot your VsCode settings ?

**Comment by redsigma** [comment]
> I made a little update, and tested it: it works on my side with a .groovylintrc.json in `C:/tmp` Please can you install latest version and screenshot your VsCode settings ?

I reinstalled the vscode extension from here `https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint` to be sure i am using a clean install. 

Unfortunately it's still not working if i change the path of `.groovylintrc.json` 

my vs-code settings.json

```json
{
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "editor.snippetSuggestions": "bottom",
    "workbench.iconTheme": "vscode-great-icons",
    "workbench.editor.languageDetection": false,
    "vsicons.dontShowNewVersionMessage": true,
    "files.trimTrailingWhitespace": true,
    "files.exclude": {
        "**/._**": true
    },
    "search.exclude": {
        "**/._**": true
    },
    "groovyLint.basic.config": "/home/red/.config/.groovylintrc.json"
}
```
If i put the `.groovylintrc.json` in my $HOME directory then everything works as expected. I also noticed that if i put the `.groovylintrc.json` file in both $HOME directory and $HOME/.config/.groovylintrc.json, then the one from $HOME will be used.
