### ISSUE TITLE
Use as module -> Failed to compile.

### ISSUE THREAD

**Issue by Sirros** [nvuillam/vscode-groovy-lint#128]
./node_modules/npm-groovy-lint/lib/groovy-lint.js 16:16
Module parse failed: Unexpected token (16:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class NpmGroovyLint {
|    "use strict";
| 
|     options = {}; // NpmGroovyLint options

**Comment by nvuillam** [comment]
What is your installed node.js version ?

**Comment by Sirros** [comment]
@nvuillam  node version： v14.17.6

**Comment by nvuillam** [comment]
I have the same version and it's ok...
What could I do to reproduce this error ?

**Comment by Sirros** [comment]
@nvuillam i use it in a vue project（single file components）

**Comment by nvuillam** [comment]
@Sirros unfortunately npm-groovy-lint / VsCode Groovy Lint rely on calling CodeNarc via java, so it's not possible to embed it on browser side
