### ISSUE TITLE
log4j usage - ctitical?!

### ISSUE THREAD

**Issue by Robaert-codes** [nvuillam/vscode-groovy-lint#132]
Hi!

Pretty clueless here myself, 
but I found the extension (version 1.6.0) brought **log4j**-*-**2.13.0**.jar|s to my machine -
which has the vulnerability the net is worried about the last days. 
See https://thehackernews.com/2021/12/extremely-critical-log4j-vulnerability.html if you did not hear about it yet.
(looks like used by slf4j)

Could you update that dependency to 2.15, which is deemed safe?

I appreciate your effort.

Regards,
Robert

**Comment by nvuillam** [comment]
@Robaert-codes > Released in 1.7.0 :)

https://github.com/nvuillam/vscode-groovy-lint/releases/tag/v1.7.0

**Comment by Robaert-codes** [comment]
Cool! Thanks for your quick reaction!

**Comment by nvuillam** [comment]
You're welcome :)
