### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by deadeuzesse** [nvuillam/vscode-groovy-lint#148]
- Issue Type: `Bug`
- Extension Name: `vscode-groovy-lint`
- Extension Version: `1.7.5`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.64.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 134,
		"activateCallTime": 5,
		"activateResolvedTime": 21,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "NicolasVuillamy.vscode-groovy-lint",
				"_lower": "nicolasvuillamy.vscode-groovy-lint"
			},
			"activationEvent": "onLanguage:groovy"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```
Every time i edit a groovy file, it makes a java runtime window pop :
![image](https://user-images.githubusercontent.com/6496280/157689160-72f31fc0-d18b-4cd4-9eaa-0e34ebf09da4.png)

**Comment by nvuillam** [comment]
Glad the update solved the issue :)
