### ISSUE TITLE
Stuck on "GroovyLint is analyzing code"

### ISSUE THREAD

**Issue by kjr6721** [nvuillam/vscode-groovy-lint#157]
Hello, thanks for making this extension! 
I am trying to use it (and it works great on some of my files) but on two it is stuck on this message:
[{
	"resource": ****,
	"owner": "GroovyLint0",
	"code": "GroovyLintWaiting",
	"severity": 2,
	"message": "GroovyLint is analyzing code...",
	"source": "GroovyLint",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

Any idea why this is happening on only some files and how I can fix it?

**Comment by verheyenkoen** [comment]
Same issue. Any progress?

**Comment by nvuillam** [comment]
Hello
Please can you share what you see in VsCode  tab "Output", category GrooyvLint ?

**Comment by kjr6721** [comment]
```
Start analyzing file:///<File_Path>/<File_Name>.groovy
Completed analyzing file:///<File_Path>/<File_Name> in 1712 ms
```

**Comment by verheyenkoen** [comment]
Same here (bit faster though):

```
Start analyzing file:///Users/verheyenkoen/Projects/ugent/tools/groovy-linter/script.groovy
Completed analyzing file:///Users/verheyenkoen/Projects/ugent/tools/groovy-linter/script.groovy in 332 ms
```

**Comment by nvuillam** [comment]
Would it be possible to share the groovy files you try to analyze so I can try to reproduce the problem locally ?

**Comment by kjr6721** [comment]
Unfortunately I am unable to share the files

**Comment by verheyenkoen** [comment]
I'll email you the problematic script. It was the first file I opened upon installing on a cleanly installed laptop that caused this so I figured it was an installation problem but now I've opened a few more and then it works.

**Comment by nvuillam** [comment]
thanks to @verheyenkoen 's script, I succeeded to reproduce.
The issue that that diagnostics are well sent to VsCode extension, but they are not displayed like with the other files, so the previous "fake" diagnostic saying that the lint is in progress is not replaced by the real errors

I investigate...

**Comment by nvuillam** [comment]
Fixed it in v1.9.1 :) (you'll need to reload VsCode once the patch is automatically installed)

![image](https://user-images.githubusercontent.com/17500430/183518910-a66fd1af-b75b-45b3-8717-eae98edf527f.png)

@verheyenkoen @kjr6721 please let me know if it's now ok on your side :)

If it is, don't hesitate to rate the extension -> https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint

**Comment by verheyenkoen** [comment]
@nvuillam That fixed it for me. Great work. Thanks very much!

**Comment by nvuillam** [comment]
Thanks for your feedback:)
