### ISSUE TITLE
VSCodium Support

### ISSUE THREAD

**Issue by tschlue** [nvuillam/vscode-groovy-lint#158]
I can't find this extension in VSCodium. When I add it manually it looks like it has some problems like adding file exceptions.

It would nice to see this open source extension works also with the open source version of vscode.

**Comment by nvuillam** [comment]
I didn't know about vscodium ^^
Does it have a dedicated marketplace ?

**Comment by tschlue** [comment]
As I found out [here](https://www.roboleary.net/tools/2022/05/31/vscode-vscodium-which-should-i-use.html) (In the middle of the page, in the table), the marktplace of vscodium is based the open vsx registry.

**Comment by nvuillam** [comment]
Got it :)

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

I'll do that in the next days :)

**Comment by tschlue** [comment]
Nice, thank you

**Comment by tschlue** [comment]
Maybe you can look also at this:

If I add a file exception I get the following error

`[Error - 12:16:26] Request workspace/executeCommand failed.
  Message: Request workspace/executeCommand failed with message: Invalid count value
  Code: -32603 `

**Comment by nvuillam** [comment]
https://open-vsx.org/extension/NicolasVuillamy/vscode-groovy-lint

This is done :)

**Comment by tschlue** [comment]
Thank you for that. Should I create a bug for the error?

**Comment by nvuillam** [comment]
Yes please, one issue = one topic :)
