### ISSUE TITLE
GroovyLint: Unable to start CodeNarc Server [MacOS]

### ISSUE THREAD

**Issue by yuvmel** [nvuillam/vscode-groovy-lint#16]
Hi, using version 0.6.3 on MacOS 10.15.4 with the following tool versions:

- nodejs 12.16.1
- java adopt-openjdk-11.0.6+10
- groovy apache-groovy-binary-3.0.2

I'm getting this output message right after starting to lint:
>GroovyLint: Unable to start CodeNarc Server. Use --noserver if you do not even want to try

I'd like to make it work please (and see if it may improve the linting & formatting performance...) - could you please help?

Thanks for publishing this promising extension! It'd be great if you could list all the required dependencies before installation please :)

**Comment by yuvmel** [comment]
[2020-04-06T20_50_44_054Z-debug.log](https://github.com/nvuillam/vscode-groovy-lint/files/4440768/2020-04-06T20_50_44_054Z-debug.log)

Log is attached, thanks for checking this!
Maybe its indeed a Mac thing (got it from work), but I learned the hard way (via vscode output pane) that I had to install node, then java (Mac has stub binaries that popup a message to install a tool, e.g. java) & finally groovy, to solve #6 :)

**Comment by nvuillam** [comment]
I apologize,  I forgot that when you use npm-groovy-lint locally, you need to build the groovy part (codenarc server) to be able to run it.

The good order is :
- npm install jdeploy -g
- npm install
- npm run build
- npm run test

Please can you try again ?

**Comment by yuvmel** [comment]
Thanks, I ran the following now:
```
npm install jdeploy -g
npm install
npm run build
npm run test 2>&1 | tee test2.out
zip test2 test2.out /Users/yuval.melamed/.npm/_logs/2020-04-07T05_50_07_489Z-debug.log
```
And attaching: 
[test2.zip](https://github.com/nvuillam/vscode-groovy-lint/files/4442288/test2.zip)

**Comment by yuvmel** [comment]
Thanks! I ran the following now:
```
npm install jdeploy -g
npm install
npm run build
npm run test 2>&1 | tee test2.out
zip -j test2 test2.out ~/.npm/_logs/2020-04-07T05_50_07_489Z-debug.log
```
And attached: [test2.zip](https://github.com/nvuillam/vscode-groovy-lint/files/4442307/test2.zip) 🙏

**Comment by nvuillam** [comment]
Ok, so the good news is that most of the tests are passing
```
65 passing (7m)
14 failing
```

The bad news is that there is an execution error because of some permissions issue, and i know few about permission issues on MAC 😨 
```
     Error: Command failed: npm-groovy-lint --path "jdeploy-bundle/lib/example" --files 
**/SampleFileSmall.groovy --loglevel warning --verbose
/bin/sh: /Users/yuval.melamed/.asdf/installs/nodejs/12.16.1/.npm/bin/npm-groovy-lint: Permission denied
```

Can you try to add exec rights and try again ? 
`chmod +x /Users/yuval.melamed/.asdf/installs/nodejs/12.16.1/.npm/bin/npm-groovy-lint`

I'll get my girlfriend's laptop today to try to reproduce

**Comment by yuvmel** [comment]
After `chmod 755 ...` things improved:

> 75 passing (7m)
> 4 failing
> 

[test3.zip](https://github.com/nvuillam/vscode-groovy-lint/files/4442855/test3.zip)
Perhaps the permission issue has to do with installing the `npm` package globally?
Could it work locally? Thanks! I appreciate your efforts :)

**Comment by nvuillam** [comment]
> Thanks! I appreciate your efforts :)
The thanks are for you, I really appreciate your time so the package can run on every platform :) 

I tried to build my first mac based CircleCI build, but it's not available on free plan :'(
I tried a little fix, can u check out branch https://github.com/nvuillam/npm-groovy-lint/tree/FixRunOnMacOs and see if it works better ?

**Comment by nvuillam** [comment]
tu peux lire le fichier et faire un echo , dans le groovy ^^

**Comment by yuvmel** [comment]
Thanks, at first it was down to 68 passing, but another `chmod` made it 78:
[test4.zip](https://github.com/nvuillam/vscode-groovy-lint/files/4443505/test4.zip)

**Comment by nvuillam** [comment]
Ok, that means that with your config, the CodeNarc Server can not be launched, but direct call to CodeNarc class is working ( but as it loads all jars at each call, it must be dramatically slow )

I detected the same issue with Linux on CicleCI builds , so there is some permission to manage somewhere for Linux & Mac ... 

To avoid that, I use a tiny httpServer ( https://github.com/nvuillam/npm-groovy-lint/blob/master/groovy/src/main/com/nvuillam/CodeNarcServer.groovy ) so jars remain loaded, and only the first call has bad performances

What if you try `npm run groovy:run-server-from-source` ?

**Comment by yuvmel** [comment]
`npm run groovy:run-server-from-source 2>&1 | tee test5.out` failed - attaching:
[test5.zip](https://github.com/nvuillam/vscode-groovy-lint/files/4444086/test5.zip)
LMK if I ran it out of context...
And indeed, the linting in VS is currently quite slow (8-20s).

**Comment by nvuillam** [comment]
![image](https://user-images.githubusercontent.com/17500430/78668187-84890f80-78da-11ea-85f3-c9a0d1aeba6c.png)
Ok... so it seems that i just can't run CodeNarcServer.groovy on Linux/Mac , compiled or not, because it doesn't find `class org.codenarc.CodeNarc`, whereas it is clearly in the classpath of the call... 
( `lib/CodeNarc-1.5.jar`  ) 

Do you have any clue about why ? :/ 
It works like a charm on Windows :'(

**Comment by yuvmel** [comment]
Yes, it seems like a known Linux/macOS (aka OSX) issue - found these issues now:
https://github.com/CodeNarc/CodeNarc/issues/159
https://github.com/CodeNarc/CodeNarc/issues/187
It might be related to a wrong delimiter in class path - `;` vs. `:`?
Also, might worth mentioning, I noticed here: https://github.com/CodeNarc/CodeNarc
That it mentions some dependency in class path:

> CodeNarc requires
> 
> Groovy version 2.1 or later
> The SLF4J api/implementation jars, accessible on the CLASSPATH.
> The GMetrics jar, version 1.0 or later -- optional if using some of the size/complexity rules.
> 

I haven't installed the last 2 - should I?

**Comment by nvuillam** [comment]
The related JARS are all embedded, no need to do more than npm install npm-groovy-lint -g :)
That''s why it's supposed to work .... ^^
I'm about to try on my Raspberry Pi, i'm pretty confident that if I solve the CodeNarcServer issue for Linux, it will also solve for mac :)

**Comment by nvuillam** [comment]
Just released v0.7.0 containing npm-groovy-lint v4.0.0 :)

**Comment by nvuillam** [comment]
+ Lint folder command :) #17

The issue was mainly on the jar generation of CodeNarcServer and local ip adddress used by it ... 

@yuvmel  please can you test on your mac and reopen the issue if the problem is still here ? 😍

**Comment by yuvmel** [comment]
Thank you so much for this quick fix! There's still something left - resembles #6 - LMK if we should continue there:
```
Start linting file:///XXX/Jenkinsfile
GroovyLint: Started CodeNarc Server after 1 attempts
Completed linting file:///XXX/Jenkinsfile in 10831 ms
[Error - 7:56:11 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'split' of undefined
  Code: -32603 
```

**Comment by nvuillam** [comment]
I created a new issue with your description :)

I'll try to see how we can activate debug logs so we can have more complete info to investigate :)

**Comment by nvuillam** [comment]
@yuvmel I posted for you on https://github.com/nvuillam/vscode-groovy-lint/issues/18 , please can you have a look ? ( can't highlight you there as u didn't comment the new issue yet )
