### ISSUE TITLE
vscode-groovy-lint consumes all memory and cpu

### ISSUE THREAD

**Issue by shadycuz** [nvuillam/vscode-groovy-lint#162]
Hello =), 

For a long time now I have had issues with my vscode and WSL2 having poor performance when working with groovy files. For the longest time, I thought it was my extension [groovy-guru](https://github.com/DontShaveTheYak/groovy-guru) 😂. As I added more groovy files to [jenkins-std-lib](https://github.com/DontShaveTheYak/jenkins-std-lib) the performance got worse, until it began crashing vscode and sometimes WSL2. I eventually got sick of the crashing and disabled my extension and to my surprise it got a little better but the crashing still remained. So I disabled `vscode-groovy-lint` and its been more than 1-month crash free. But I miss `vscode-groovy-lint`.

I'm not sure what's causing the issue but I have some ideas. It seems to me that `vscode-groovy-list` is trying to scan/lint every groovy file in my workspace instead of just the open groovy files. This leads to it spawning many 10 or 20+ `java` processes. I think they were java processes, don't recall clearly. Since my library has lots of `.groovy` files, it quickly consumes all my memory and slows my system down.

I think there are a number of solutions. Like making `vscode-groovy-lint` only lint open files or detecting large amounts of groovy files and batching them together in groups of 5 or something. If I remember right, this extension is only a wrapper around a CLI tool, so its possible none of my ideas will work but maybe you know of a config setting for the underlying tool that will help. 

Just wanted to let ya know =) 

Thanks @nvuillam

**Comment by nvuillam** [comment]
That's unfortunately a known issue :/

VsCode Groovy Lint calls npm-groovy-lint , which calls CodeNarc
CodeNarc can not accept a given list of files, only Ant-style pattern, so I suspect it can be a cause of the performance issues 

I'll try to solve that by making a PR in CodeNarc :) https://github.com/CodeNarc/CodeNarc/issues/714

**Comment by shadycuz** [comment]
@nvuillam I think that implementing in CodeNarc is probably the correct way and a much-needed feature. I have had a similar problem with other static code analysis tools that refuse to work on individual files.

but... there is a darker and dirtier path to fixing this issue. Every extension has its own "directory" for files. You could create a directory there called `workspace` or w/e. Then you could take the files open in vscode editor and copy them to that directory and run `CodeNarc` on that entire directory. 

You would also have to make sure that when a groovy file is closed in the editor, its removed from that directory and you would need to keep the files in sync. But I believe vscode api makes these things pretty easy? But this is a pretty hacky workaround.

**Comment by ysmaoui** [comment]
hi @nvuillam 

I see your PR has in CodeNarc has been merged
does this need to be ported here?

I am still getting this performance issue with a lot of groovy files in my vscode workspace
I had to disable groovy lint

**Comment by shadycuz** [comment]
@nvuillam Just a friendly reminder that a new CodeNarc version has been released =) 

https://github.com/CodeNarc/CodeNarc/releases/tag/v3.2.0

**Comment by nvuillam** [comment]
It's in the pipe :)

**Comment by shadycuz** [comment]
Noice =), close this when ever ya want.

**Comment by nvuillam** [comment]
@shadycuz  this is fixed in newest release v3.0.0, thanks to the great job of @stevenh :)

Please can you confirm it works well for your case now ?
- If yes, please rate the app -> https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint&ssr=false#review-details
- If not, please reopen the issue and we'll check :)
