### ISSUE TITLE
Linting is much slower than npm-groovy-lint

### ISSUE THREAD

**Issue by stevenh** [nvuillam/vscode-groovy-lint#174]
I often see a list of files queued for linting in VS code which take a long time.

I've tested using `npm-groovy-lint` directly and this seems to be a lot quicker, for example a single Jenkinsfile with 1100 lines takes `vscode-groovy-lint` over 5 seconds whereas `npm-groovy-lint` direct is just over a second with all files being checked in just of 6 seconds.

I've tried to see exactly what `vscode-groovy-lint` is running, but it doesn't seem to say even with debug and verbose enabled.

Any tips on debugging what the difference might be?

**Comment by nvuillam** [comment]
The main problem is in npm-groovy-lint , which is half-broken for a while, and i can't really find why as i'm rusty in java / groovy :/

**Comment by stevenh** [comment]
Ok I've made some progress on this, seems it reports timing even when it errors out and it's not actually running properly due to a binding issue.

I believe I know how to fix but would be great if you tell me how to get `npm-groovy-lint` debug to appear in `Groovy Lint` output log when debug is enabled. Any pointers on that as I'm not familiar with creating vs code extensions.

**Comment by nvuillam** [comment]
@stevenh you can follow these instructions and add breakpoints :)

https://github.com/nvuillam/vscode-groovy-lint/blob/master/CONTRIBUTING.md

Please let me know if u need more ibfo :)

**Comment by stevenh** [comment]
Thanks @nvuillam continuing to make progress, found and fixed at least a few bugs, I think at least one is in [CodeNarc](https://github.com/CodeNarc/CodeNarc), but just updating to the latest version to see.

**Comment by nvuillam** [comment]
You are a hero to the groovy community ❤️
If you make npm-groovy-lint & vscode-groovy-lint i'll ask u yo be co-maintainer 🎉

**Comment by stevenh** [comment]
I definitely have the both building, as they will both need fixes.

I love the option to update `vscode-groovy-lint` from `npm-groovy-lint` by the way 😄

**Comment by stevenh** [comment]
Think I finally have all the fixes, as there's a combination of things I'll split it up into a few PR's that fix each of the bugs.

**Comment by stevenh** [comment]
Ok all the fixes for npm-groovy-lint have PR's. The main one seems like it was IPv6 fix which was causing request to fail, but there where a bunch of others that caused random failures making it look like things were slow when in fact failures happening.

One the npm-groovy-lint changes are merged and a new release made I can do a PR to bump the dependencies alongside the  other PRs to this repo.

Locally with all these fixes it's been solid and performing well :)

**Comment by nvuillam** [comment]
@stevenh plz accept me on Linkedin ;)

**Comment by nvuillam** [comment]
@stevenh it seems it is fixed now, right ?

I made tests on my computer and the results were satisfying :)
