### ISSUE TITLE
codeAction failed with message: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by nvuillam** [nvuillam/vscode-groovy-lint#18]
Thank you so much for this quick fix! There's still something left - resembles #6 - LMK if we should continue there:
```
Start linting file:///XXX/Jenkinsfile
GroovyLint: Started CodeNarc Server after 1 attempts
Completed linting file:///XXX/Jenkinsfile in 10831 ms
[Error - 7:56:11 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'split' of undefined
  Code: -32603 
[Error - 8:04:31 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'split' of undefined
  Code: -32603 
[Error - 8:04:33 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'split' of undefined
  Code: -32603 
```
EDIT: (Only) the last error seems to repeat after visiting the file again (without changes - no new linting), if it may help you pinpoint the issue ;-)

_Originally posted by @yuvmel in https://github.com/nvuillam/vscode-groovy-lint/issues/16#issuecomment-611329234_

**Comment by nvuillam** [comment]
I just released v0.7.1 with new option "debug mode"
It will spit lots of debug logs, please can you active it then send me the logs when you reproduce the `Cannot read property 'split' of undefined` bug ?

![image](https://user-images.githubusercontent.com/17500430/78884121-baed9880-7a5a-11ea-9f80-76d4e9bf6c10.png)

**Comment by yuvmel** [comment]
Thanks! Sure:
[debug1.log](https://github.com/nvuillam/vscode-groovy-lint/files/4455819/debug1.log)

**Comment by nvuillam** [comment]
mmm i don't see errors there :/
Maybe it's related to a particular error ... please could I have  the file you are trying to lint ?
If you do not wish to post it publicly, you can write me at nicolas.vuillamy@gmail.com , I promise i'll keep it for myself ^^

**Comment by yuvmel** [comment]
Hi, I noticed the filename appears in the log, so this is why I chose a non-private file in the first place - it was `CodeNarcServer.groovy` from the (now obsolete) branch you sent me ;-)
Anyway, this error appear with all files - Jenkinsfile & groovy. You believe it's different than #6? Maybe throw some more debug prints - I can run again & send you, gladly, I'd love to make this work :)
BTW - might be related, or maybe another issue - I noticed that also formatting seems partial - I inserted some extra blank lines & spaces around operators - the redundant blank lines were indeed gone, but the over-spaced expressions were not. Maybe something crashes in background? LMK if I should try a "format" in debug mode too, or maybe it warrants a new issue? Thanks!

**Comment by nvuillam** [comment]
@yuvmel I tried something in v 0.7.3 ... can't promise it will work, but there are good chances it does :)
Please can you check ? :)

**Comment by yuvmel** [comment]
Hi @nvuillam, I replicated it both on 0.7.3 (it's called 0.7.2 in VS change-log, BTW) and the fresh 0.8.1 but I think I found a pattern you may replicate too - it happens when using the [cSpell](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension (and enabling it for Groovy & Jenkinsfile) and when both cSpell and GroovyLint find issues on the same line of code - here is my entire Jenkinsfile:
```
pipeline {
    options {
        buildDiscarder(logRotator(daysToKeepStr: '5', numToKeepStr: '5'))
    }
    stages {
        stage('Greetings') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
```
With cSpell disabled, GroovyLint works fine - from its debug output:
```
2020-04-13T05:59:50.343Z vscode-groovy-lint Code action request received from client for file:///Users/yuval.melamed/Jenkinsfile with params: {"textDocument":{"uri":"file:///Users/yuval.melamed/Jenkinsfile"},"range":{"start":{"line":2,"character":31},"end":{"line":2,"character":31}},"context":{"diagnostics":[{"range":{"start":{"line":2,"character":8},"end":{"line":2,"character":73}},"message":"Duplicate String Literal: 5","severity":2,"code":"DuplicateStringLiteral-1","source":"GroovyLint"}]}}
2020-04-13T05:59:50.344Z vscode-groovy-lint Provided 2 codeActions for file:///Users/yuval.melamed/Jenkinsfile
```
With cSpell enabled:
```
2020-04-13T06:00:43.146Z vscode-groovy-lint Code action request received from client for file:///Users/yuval.melamed/Jenkinsfile with params: {"textDocument":{"uri":"file:///Users/yuval.melamed/Jenkinsfile"},"range":{"start":{"line":2,"character":8},"end":{"line":2,"character":73}},"context":{"diagnostics":[{"range":{"start":{"line":2,"character":8},"end":{"line":2,"character":73}},"message":"Duplicate String Literal: 5","severity":2,"code":"DuplicateStringLiteral-1","source":"GroovyLint"},{"range":{"start":{"line":2,"character":13},"end":{"line":2,"character":22}},"message":"\"Discarder\": Unknown word.","severity":3,"source":"cSpell"}],"only":["quickfix"]}}
[Error - 9:00:43 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'split' of undefined
  Code: -32603 
```

**Comment by nvuillam** [comment]
Reproduced ! :)
I'm on it ^^

**Comment by nvuillam** [comment]
@yuvmel  you can try 0.8.2 :)
I added a new README paragraph especially for you :)

![image](https://user-images.githubusercontent.com/17500430/79102999-1d50dc80-7d6c-11ea-8ed5-86c93ea6ca16.png)
