### ISSUE TITLE
file ''logback.log' created automatically while open any new vscode window

### ISSUE THREAD

**Issue by yangjuexi-ones** [nvuillam/vscode-groovy-lint#200]
Type: <b>Bug</b>

1. install the extension
2. open any folder by vscode
3. a file named 'logback.log' will be created automatically  at the root path of folder

Extension version: 3.1.0
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 8, 7|
|Memory (System)|8.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 66ed805b-18ab-405c-9152-8c330a1ab0ae|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pythonregdiag2:30926735
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by superelitist** [comment]
I also experience this issue. I just noticed it happening now, probably because I reopened VSCode and it took the opportunity to update/restart extensions.

**Comment by l3ender** [comment]
Seeing the same thing. The `logback.log` file is in the root directory of the folder. It's empty, but can't be deleted until VS Code is closed. I've accidentally added it to source control a few times. :(

**Comment by perunslava** [comment]
Simple workaround:
1. echo "logback.log" > ~/.gitignore
2. git config --global core.excludesFile '~/.gitignore'

**Comment by cloudwitch** [comment]
This is obnoxious. My coworkers keep getting onto me for accidentally committing this. I've got it on my global gitignore now, would like to remove.

**Comment by shygnome** [comment]
I have the same issue. May need to revert to the older version.

**Comment by KrzysztofBuchacz** [comment]
Same problem, quite annoying.

**Comment by nvuillam** [comment]
We'll have a look , meanwhile I suggest you follow @perunslava 's workaround and add logback.log in gitignore :)

cc @stevenh
