### ISSUE TITLE
Never option on tab warning isn't "sticky"

### ISSUE THREAD

**Issue by stretch327** [nvuillam/vscode-groovy-lint#203]
When you first open a groovy file and get the warning that says:

"CodeNarc linter doesn't like tabs, let's replace them by spaces ?"

The options that are available are "Always, Yes, No and Never"

If you select Never, it is treated as if you clicked "No" and you still have to answer this question again each time you open a new document.

**Comment by stretch327** [comment]
Stale because you haven't looked at it?

**Comment by nvuillam** [comment]
@stretch327 indeed !

We are mostly 2 persons ( @stevenh and myself ) to maintain vscode-groovy-lint for free, and our available time is limited... sometimes it can take time :/

Maybe you'd like to help by submitting a pull request with a fix ?

**Comment by stevenh** [comment]
Never is currently acting as no for this session vs never ask me again, what's the intended behaviour here?

**Comment by nvuillam** [comment]
@stevenh "Never again for any Groovy file i'll open with this vscode" ^^

I don't know if it's good or not, but it was the previous behaviour so people are probably used to it ^^

**Comment by stevenh** [comment]
Thanks for the confirmation. I can confirm it's only set in a session variable there is no configuration option I could find for that, let me know if I missed something @nvuillam .

If the above is correct, to fix we would need to introduce a config option for this and have the dialog option interact with that and the document handler get subscribe to config updates, so a little bit involved.

**Comment by nvuillam** [comment]
@stevenh let's check how it was done before your refactoring :)
I think i wrote the option in vscode settings

**Comment by stretch327** [comment]
Sounds like you guys have ideas how to fix it. Please keep this case open!
