### ISSUE TITLE
.groovylintrc.json not honoured anymore since latest update

### ISSUE THREAD

**Issue by kikmon** [nvuillam/vscode-groovy-lint#211]
Hi

Since the new release of the VS extension, the linter doesn't seem to take into account the configuration of my .groovylintrc.json file.
This was working fine before the update.
Am I the only only having this issue ?
Is there a new way to configure the linting rules ?

Thanks

**Comment by nvuillam** [comment]
@kikmon which release are you referring to ?

https://github.com/nvuillam/vscode-groovy-lint/releases

Nothing is supposed to have changed about `.groovylintrc.json` management, do you have an example repo so that we could reproduce the issue ?

**Comment by kikmon** [comment]
Ok, then I must have done something wrong :)
I'll try to isolate it in an test repo

**Comment by kikmon** [comment]
small update, I seemed to have used some syntax that are not supported anymore in the .groovylintrc.json
I had a string in DuplicateNumberLiteral/ignoreNumbers parameters, and it's not recognized anymore, but using a real list works fine. ("0,1,2" -> [0,1,2])
For DuplicateStringLiteral/ignoreStrings, the latest version is still using a string (strangely enough) ...
I was using a string of comma separated string like "'1','2'"
Worked perfectly until the latest updatE :) I updated the string to "1,2" and it's working fine now.
I guess the ticket can be closed :)

**Comment by nvuillam** [comment]
@kikmon thanks for your feedback :)
