### ISSUE TITLE
Support for gdsl files (intellisense addition) 

### ISSUE THREAD

**Issue by Bloodiko** [nvuillam/vscode-groovy-lint#215]
Some projects which support groovy additions have gdsl files for the additional linting, and custom objects. 

For example Artifactory User Plugins: 
https://jfrog.com/help/r/jfrog-integrations-documentation/the-artifactory-public-api-papi
https://github.com/jfrog/artifactory-user-plugins/blob/master/ArtifactoryUserPlugins.gdsl

Is it possible to include this in the Plugin, so I can utilize the additional intellisense? 

Or is this maybe already possible ? (I did not find anything with a quick search, so I have no Idea.) 

Thanks

**Comment by nvuillam** [comment]
@Bloodiko we could handle .gdsl files for formatting and linting, but not for intellisense, because VsCode Groovy Lint does not cover that area

Are you inteteste by .gdsl management anyway ? :)

**Comment by Bloodiko** [comment]
Well linting is also a good stepup. 

But don't feel pressured. 
If there's more demand for it, you may revisit this. 

It's not like this is a breaking issue or smth 🙂

**Comment by Bloodiko** [comment]
I have switched to groovy-guru (dont-shave-the-yak) for intellisense.

This helps a lot. 
So this is not needed for me anymore, since it also supports the custom jars for intellisense, basically rendering the gdsl file unnecessary.
