### ISSUE TITLE
Isn't working in Windows 11 with Java 22 and Node 20.5.11

### ISSUE THREAD

**Issue by jimtut** [nvuillam/vscode-groovy-lint#225]
% java --version
java 22.0.1 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

% C:\nvm\nvm list

  * 20.5.1 (Currently using 64-bit executable)

The plugin spins in the taskbar, but absolutely no linting messages are shown anywhere, and I have some LONG lines that should trigger warnings.

![image](https://github.com/nvuillam/vscode-groovy-lint/assets/5229799/18fdb0af-ced8-4044-88a4-22640dab0912)

**Comment by jimtut** [comment]
Captured an error message, but nothing is displayed in the Output window, despite the settings.
![image](https://github.com/nvuillam/vscode-groovy-lint/assets/5229799/50337a35-7db7-4358-8a19-0f1c852e8d50)

**Comment by nvuillam** [comment]
@jimtut do you have anything in the Groovy output ?

![image](https://github.com/nvuillam/vscode-groovy-lint/assets/17500430/622471fb-209f-48c1-b6f3-8fe953d3d07f)

npm-groovy-lint requires jdk17 but if it is not detected, it should be automatically installed in $HOME/.java-caller folder

Please can you also try to install npm-groovy-lint (`npm i npm-groovy-lint -g`) and run it at the root of your repository ?

**Comment by jimtut** [comment]
I ran that npm command:
> % npm i npm-groovy-lint -g
> added 91 packages in 23s

But, nothing happens in VS Code when linting, unless I use "Fix all auto-fixable problems", but that seems to be using CodeNarc, not this linter.

Java is installed, but should it be copied somewhere else?

> % which java.exe
> C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
> 
> % java --version
> java 22.0.1 2024-04-16
> Java(TM) SE Runtime Environment (build 22.0.1+8-16)
> Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

I wasn't seeing anything in the Output window, but then realized I needed to select a specific Output, so "Groovy Lint" shows this:

> 024-04-28T19:24:02.388Z npm-groovy-lint <<< NpmGroovyLint.run START >>>
> Start analyzing file:///c%3A/Users/tuttlj/Dev/pmpe-jenkins-library/pipeline-scripts/Dockerized_Simple_Pipeline.groovy
> 2024-04-28T19:24:02.395Z npm-groovy-lint GroovyLint used config file: c:\Users\tuttlj\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-3.3.0\server\node_modules\npm-groovy-lint\lib\.groovylintrc-recommended.json
> 2024-04-28T19:24:02.428Z npm-groovy-lint CREATE GROOVY temp file C:\Users\tuttlj\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpDir_0.14477830794653856\Dockerized_Simple_Pipeline.groovy with input source, as CodeNarc requires physical files
> 2024-04-28T19:24:02.431Z npm-groovy-lint callCodeNarcServer code: ECONNREFUSED error: connect ECONNREFUSED 127.0.0.1:7484
> 2024-04-28T19:24:02.431Z npm-groovy-lint ATTEMPT to start CodeNarcServer with --server
> Java jre or jdk 17 is required
> Installing Java jre 17 in C:\Users\tuttlj\.java-caller...
> VsCode Groovy Lint error: request to https://api.adoptopenjdk.net/v3/binary/latest/17/ga/windows/x64/jre/hotspot/normal/adoptopenjdk failed, reason: self signed certificate in certificate chain
> FetchError: request to https://api.adoptopenjdk.net/v3/binary/latest/17/ga/windows/x64/jre/hotspot/normal/adoptopenjdk failed, reason: self signed certificate in certificate chain
>     at ClientRequest.<anonymous> (c:\Users\tuttlj\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-3.3.0\server\node_modules\node-fetch\lib\index.js:1501:11)
>     at ClientRequest.emit (node:events:517:28)
>     at TLSSocket.socketErrorListener (node:_http_client:501:9)
>     at TLSSocket.emit (node:events:517:28)
>     at emitErrorNT (node:internal/streams/destroy:151:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Seems like there are 2 problems:

1. **Java 17**: It keeps trying to install this in .java-caller (message above keeps getting repeated), but it's really only installing a package.json files w/ the contents below.  Running "npm install java-caller --save" didn't seem to change this behavior.

> {"name":"java-caller-support","version":"1.0.0","description":"Java installations by java-caller (https://github.com/nvuillam/node-java-caller)"}

2. **Self-signed certs**: This is common at a company, but both Java and Windows have the correct CA certs to deal with this.  This installer must be using something else, although I changed the npm config too, didn't seem to help.

Conclusion: Pass the exact path to java.exe in the extension settings and all is well (even though C:\Program Files\Common Files\Oracle\Java\javapath\java.exe was on the PATH):
"groovyLint.java.executable": "\"C:\\Program Files\\Java\\jdk-17\\bin\\java.exe\""

My me, this is all that I need, but there might be some bugs in how this plugin and/or npm require/detect/use both Java and additional CA certs.
