### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by uniks37** [nvuillam/vscode-groovy-lint#235]
The plugin might be causing huge memory leak. I have been experience the memory leak since past few weeks where the plugin takes up all the resources by spamming the jvm instances. Uninstalling the plugin, however, recovers the system CPU load and frees up memory.

**Comment by nvuillam** [comment]
@uniks37 VsCode Groovy lint relies on npm-groovy-lint, who launches a local server via JVM, then interrogates it via HTTP calls

I always noticed that CodeNarc (behind npm-groovy-lint) has a heavy memory usage... except creating the local server, I never found a real solution as I'm not java expert

Would you know how to detect from where the memory leak is from, so we could fix it (or maybe directly in CodeNarc) ?

cc @stevenh

**Comment by stevenh** [comment]
Java us just heavy, without more details hard to say what's happening. I've never noticed a particular issue.
