### ISSUE TITLE
Add option to send --no-parse to npm-groovy-lint

### ISSUE THREAD

**Issue by nvuillam** [nvuillam/vscode-groovy-lint#243]
Related to https://github.com/nvuillam/npm-groovy-lint/issues/406

**Comment by Fabi9199** [comment]
Maybe think of adding an option "args" to the vscode extension settings, then every user can add the arguments by himself :)

**Comment by nvuillam** [comment]
@Fabi9199 npm-groovy-lint is called as module., not command line ^^
For the moment inm struggling because after spending hours to refactor npm-groovy-lint as a modern ES Module, I discovered that VsVode extensions can not import them... 🤡🤡
