### ISSUE TITLE
Comparison of .groovy files exits unexpectedly

### ISSUE THREAD

**Issue by jonathan-al** [nvuillam/vscode-groovy-lint#251]
Hello,  
I'm encountering an issue when comparing two `.groovy` files using the vscode-groovy-lint extension in VS Code. When initiating the file comparison, the comparison view unexpectedly closes, and the editor returns to the original file used as the comparison reference, rather than staying in the comparison mode.

Steps to reproduce:  
1. Open two `.groovy` files in VS Code.  
2. Start a comparison between the two files.  
3. Observe that the comparison view exits unexpectedly, returning to the reference file.

System details:  
- VS Code version: 1.95.2
- vscode-groovy-lint version: v3.3.1
- OS: macOS 14.6.1 (23G93)

Please let me know if additional details or logs are needed. Thank you for looking into this!

**Comment by lukasnee** [comment]
Hey @jonathan-al, maybe you've been able to resolve this issue yourself? I'm facing the same, it is so annoying :D
