### ISSUE TITLE
vscode-groovy-lint-0.10.0' as it is not compatible with VS Code '1.30.2'

### ISSUE THREAD

**Issue by lbourgeois76** [nvuillam/vscode-groovy-lint#32]
Hello,

I try to install your very intersting plugin on the last VSCODE version but I have got this problem.

Unable to install extension 'nicolasvuillamy.vscode-groovy-lint-0.10.0' as it is not compatible with VS Code '1.30.2'.

Regards,

**Comment by nvuillam** [comment]
You need node.js v12 minimum, what is your node version ?

If it is >= 12, what is the error message ? (Output -> GroovyLint)

Le mar. 5 mai 2020 à 14:40, lbourgeois76 <notifications@github.com> a
écrit :

**Comment by nvuillam** [comment]
@lbourgeois76  > VsCode current version is currently  1.44 ... I think if you just upgrade to it, it will be ok :)

https://code.visualstudio.com/updates/v1_44

![image](https://user-images.githubusercontent.com/17500430/81080014-91584d80-8ef0-11ea-8ee5-2d815fd06874.png)

**Comment by lbourgeois76** [comment]
> @lbourgeois76 > VsCode current version is currently 1.44 ... I think if you just upgrade to it, it will be ok :)
> 
> https://code.visualstudio.com/updates/v1_44
> 
> ![image](https://user-images.githubusercontent.com/17500430/81080014-91584d80-8ef0-11ea-8ee5-2d815fd06874.png)

I confirme, I have install on my computer nodeJS 12 and Install the 1-44 version.
Now the installation is ok.

Thanks

**Comment by nvuillam** [comment]
You're welcome :)
Have fun and do not hesitate to post new issues if you see problems :)
