### ISSUE TITLE
Unable to start CodeNarc Server

### ISSUE THREAD

**Issue by jmcfallargo** [nvuillam/vscode-groovy-lint#38]
Looking for help with an error running analyze.  I originally saw this error running VSCode in remote mode via SSH, but I confirmed that I get the same error directly on the remote machine.
I have NPM 12 installed ( on both local and remote machines).  (I have removed any identifying info such as IPs)

GroovyLint: Unable to start CodeNarc Server. Use --noserver if you do not even want to try
CodeNarcServer http call unexpected error:
{
  "name": "RequestError",
  "message": "Error: connect ECONNREFUSED 172.x.y.z:7484",
  "cause": {
    "errno": "ECONNREFUSED",
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "172.x.y.z",
    "port": 7484
  },
  "error": {
    "errno": "ECONNREFUSED",
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "172.x.y.z",
    "port": 7484
  },
  "options": {
    "method": "POST",
    "uri": "http://172.x.y.z:7484/request",
    "body": {
      "codeNarcArgs": "-basedir=/tmp/npm-groovy-lint/codeNarcTmpDir_0.7705393990443135 -rulesetfiles=file:/tmp/npm-groovy-lint/codeNarcTmpRs_0.8503429860780096.groovy -includes=**/regression.groovy -report=xml:/tmp/npm-groovy-lint/codeNarcReportXml_0.4252318666148276.xml",
      "parse": true,
      "file": "/tmp/npm-groovy-lint/codeNarcTmpDir_0.7705393990443135/regression.groovy",
      "requestKey": "/home/user/src/pipeline/pipelines/regression.groovy-none"
    },
    "timeout": 360000,
    "json": true,
    "simple": true,
    "resolveWithFullResponse": false,
    "transform2xxOnly": false
  }
}
GroovyLint: Error running CodeNarc: 
/bin/sh: 1: node: not found

**Comment by nvuillam** [comment]
This `node not found` is strange... what OS/version are you using ?

Are you on a docker image ?

**Comment by nvuillam** [comment]
I think there is an issue with node-jre package, which is supposed to install java automatically when it is not here: it is deprecated

Can you stry again after installing Java ? ( 8 or 11 are tested via CI, but any version > 8 should work )

**Comment by nvuillam** [comment]
I updated the extension so that node is not called anymore, but a fork is instead
@jmcfallargo please can you confirm it is ok now ?

**Comment by jmcfallargo** [comment]
Confirmed - it now works!  Thanks for the help on this!

I did have Java installed locally, before I encountered this issue.

**Comment by nvuillam** [comment]
Great, thanks for your feedback and have fun grooving :)
