### ISSUE TITLE
Extension should use Formatters category in VSCode

### ISSUE THREAD

**Issue by JeremyKennedy** [nvuillam/vscode-groovy-lint#41]
When viewing a Jenkinsfile and attempting to format, I see a message saying no formatters are installed. There is a button to install a formatter, which opens a VSCode extension search for "category:formatters groovy". This extension doesn't appear there, but it should! 

Thanks for creating this extension, it seems to work pretty well!

**Comment by nvuillam** [comment]
Never had this bug, ... what is your os ? Are you using the latest version
of vscode ?


Le mar. 19 mai 2020 à 22:32, Jeremy Kennedy <notifications@github.com> a
écrit :

**Comment by nvuillam** [comment]
Oops sorry  understood wrong, u're not posting an issue but an advice :)
I'll wait for v1.0.0 and ask vscode if they want to bring this package aboard :)

**Comment by JeremyKennedy** [comment]
Yep, no issues with the functionality of the extension itself, it works
great for my needs!

Thank you!

**Comment by nvuillam** [comment]
Published in version 0.15.0 , thanks for the tip :)
