### ISSUE TITLE
Cannot read property 'title' of null

### ISSUE THREAD

**Issue by baruchiro** [nvuillam/vscode-groovy-lint#44]
```
VsCode Groovy Lint error: Cannot read property 'title' of null
TypeError: Cannot read property 'title' of null
    at Object.<anonymous> (c:\Users\BaruchR\.vscode-insiders\extensions\nicolasvuillamy.vscode-groovy-lint-0.15.1\server\out\linter.js:186:33)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\BaruchR\.vscode-insiders\extensions\nicolasvuillamy.vscode-groovy-lint-0.15.1\server\out\linter.js:5:58)
[Error - 2:10:14 PM] Request workspace/executeCommand failed.
  Message: Request workspace/executeCommand failed with message: Cannot read property 'map' of undefined
  Code: -32603 
VsCode Groovy Lint error: Cannot read property 'title' of null
TypeError: Cannot read property 'title' of null
    at Object.<anonymous> (c:\Users\BaruchR\.vscode-insiders\extensions\nicolasvuillamy.vscode-groovy-lint-0.15.1\server\out\linter.js:186:33)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\BaruchR\.vscode-insiders\extensions\nicolasvuillamy.vscode-groovy-lint-0.15.1\server\out\linter.js:5:58)
```

Which more details you need?

**Comment by nvuillam** [comment]
I released a new version with major updates, do you still have the issue ?
If yes, please can you post a full log after activating groovylint debug setting ? :)

**Comment by nvuillam** [comment]
@baruchiro , is the problem still happening ?
Without response, I'll close the issue :)

**Comment by nvuillam** [comment]
No response... I consider the issue is solved :)
Please reopen it if you still see the problem :)

**Comment by baruchiro** [comment]
I haven't had time to test it yet. I think it's still happening, but I'll
check it out.

**Comment by baruchiro** [comment]
Please open this issue again, or maybe open another issue since this log seems different.

[groovylint.log](https://github.com/nvuillam/vscode-groovy-lint/files/4707555/groovylint.log)

**Comment by baruchiro** [comment]
Now, this issue reproduced:

[groovylint.log](https://github.com/nvuillam/vscode-groovy-lint/files/4707595/groovylint.log)

**Comment by nvuillam** [comment]
No such property: enables for class: org.codenarc.rule.size.NestedBlockDepthRule

**Comment by baruchiro** [comment]
Right, but I don't think it is the real problem. I fixed this typo and here are the new logs:

[groovylint.log](https://github.com/nvuillam/vscode-groovy-lint/files/4707660/groovylint.log)

**Comment by nvuillam** [comment]
This is the same error, sorry the good word is **enable**, not **enabled** :/ 

`No such property: enables for class: org.codenarc.rule.size.NestedBlockDepthRule\nPossible solutions: enable`

Please can  you post your groovylintrc.json file here ?

**Comment by baruchiro** [comment]
Sorry, that was my mistake, apparently I forgot to save the file.

Now everything works!
