### ISSUE TITLE
There has been an unexpected error while calling npm-groovy-lint

### ISSUE THREAD

**Issue by litan1106** [nvuillam/vscode-groovy-lint#48]
There has been an unexpected error while calling npm-groovy-lint

**Comment by nvuillam** [comment]
Please can you provide the log in output/GroovyLint ? :)

**Comment by litan1106** [comment]
Thanks. It worked after I downgraded my java version to 11 from 14.

**Comment by nvuillam** [comment]
Thanks for the tip !
I didn't test on java 14 (CI tests are done with java 8 & 11), maybe the embedded Groovy 3.0.3 is not compliant with Java 14, i'll have a look
