### ISSUE TITLE
Looking for Auto-formater (ALT+SHIFT+F)

### ISSUE THREAD

**Issue by neelanjansinha** [nvuillam/vscode-groovy-lint#50]
Hi, I was expecting that this extension to VSCode will enable me to format indentation with keyboard shortcut (ALT+SHIFT+F). I am not sure if this is an issue, if not, please consider this as an enhancement.
Thank you!

**Comment by nvuillam** [comment]
The extension is declared as a formatter, I just tried ALT+SHIFT+F in a groovy file and it worked... that's part of what this extension can do :)

Maybe you have an error somewhere ?
Please can you have a look in Output/GroovyLint logs and post them here ? :)

**Comment by neelanjansinha** [comment]
Sorry, yes, I just realized there were errors in the Groovy script I just received from a team member.
Thanks much for such a quick response.
Have a wonderful day.

----------------------
Thanks and Regards,
Neelanjan Sinha

**Comment by nvuillam** [comment]
You're welcome, have a nice day and happy coding :)
