### ISSUE TITLE
Does not work for jenkinsfile out of the box as formatter

### ISSUE THREAD

**Issue by pkruk2** [nvuillam/vscode-groovy-lint#55]
Hi.

I wanted to format my jenkinsfile (scripted pipeline).

After running "Format Document" command, vscode said there is no formatter for jenkinsfile, and suggested to install this extension. 

After installing it "Format Document" still says there is no formatter for jenkinsfile.

**Comment by nvuillam** [comment]
Did you restart VSCode ?

**Comment by pkruk2** [comment]
I didn't. I restarted now, but still didn't help.
(Also, there was no information that restart is required - normally the "install" button changes to "reload required").

**Comment by nvuillam** [comment]
Please can you post your settings.json ?

Windows %APPDATA%\Code\User\settings.json
macOS $HOME/Library/Application Support/Code/User/settings.json
Linux $HOME/.config/Code/User/settings.json

**Comment by pkruk2** [comment]
Here is my %APPDATA%\Code\User\settings.json

```
{
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "editor.renderWhitespace": "none"
}
```

Additional information:

1. If I don't have any extensions installed, open a .jenkinsfile, use "Format document" action - vscode says _"There is no formatter for 'plaintext' files installed"_
2. If I install _secanis.jenkinsfile-support_ extension, use "Format document" action - vscode says _"There is no formatter for 'jenkins' files installed"_

**Comment by nvuillam** [comment]
I don't know those other VsCode extensions

It seems that VsCode does not detect that your Jenkinsfile are in groovy

What if you add `#!groovy` at the first list of your jenkinsfile ?

![image](https://user-images.githubusercontent.com/17500430/86333240-ee038a80-bc4b-11ea-82b2-0f78bdcca987.png)

it VsCode detects your file as groovy it should be ok

![image](https://user-images.githubusercontent.com/17500430/86333279-fb207980-bc4b-11ea-83ee-d5932cd9637d.png)

**Comment by pkruk2** [comment]
Yes, now the file is recognized the file as groovy and your extension works (there are new Problems items, formatting action accepts the file).

But maybe it's possible to recognize the file based on extension? I think it's ".jenkinsfile" normally for pipelines. I think that's how the other extensions work, they don't need the "#!groovy" comment to recognize it as a jenkinsfile.

Plus, as I mentioned above, for some reason your extension is proposed by vscode if the other extension is installed (and vscode recognizes it as "jenkinsfile").

**Comment by nvuillam** [comment]
This issue is for Visual Studio Code , because it does not automatically recognize Jenkinsfile as groovy ^^
And from an extension you can't create file types associations

You can think to add `#!groovy` at the beginning of your file , or use the following Workaround :

https://stackoverflow.com/a/36789145/7113625

**Comment by copdips** [comment]
I got it worked, in fact, my file association is considered as jenkinsfile, set the language mode to groovy resolved the issue.
@nvuillam , is there any possibilty to make the extension to work with jenkinsfile mode too ?

**Comment by nvuillam** [comment]
@copdips I just released 1.6.0 with an update that should make Jenkinsfile automatically detected

https://github.com/nvuillam/vscode-groovy-lint/pull/130

Please can you confirm it's ok on your side ?

**Comment by copdips** [comment]
@nvuillam 
it seems that v1.6.0 doesnt work neither for JenkinsFile, switching bach to Groovy makes the groovy linter to run right now. 
FYI, I can only test in VSCode remote ssh mode.

**Comment by nvuillam** [comment]
If you do a right click in an open Jenkinsfile tab, do you see groovylint commands ? (Analyze & fix)

**Comment by copdips** [comment]
Yes, i have the menu, but in JenkinsFile mode, the output is :

```log
2021-11-29T14:55:26.996Z vscode-groovy-lint Request execute command {"command":"groovyLint.lint","arguments":[{"$mid":1,"path":"/home/my_path_to_jenkinsfile/Jenkinsfile","scheme":"file"}]}
[Error - 3:55:26 PM] Request workspace/executeCommand failed.
  Message: Request workspace/executeCommand failed with message: ERROR: Document not found for URI file:///home/my_path_to_jenkinsfile/Jenkinsfile
  Code: -32603 
```

Switching back to Groovy has no issue for the same file
