### ISSUE TITLE
BracesForForLoop-0 could not be fixed

### ISSUE THREAD

**Issue by Pantastisch** [nvuillam/vscode-groovy-lint#58]
Hi,
I am experiencing an issue regarding the rule GroovyLint(BracesForForLoop-0) 

Unfortunately  vscode-groovy-lint is still reporting this issue, regardingless if it is fixed or not.
The quick fix option does not solve the issue as well...

![image](https://user-images.githubusercontent.com/45369229/85387389-105b2100-b545-11ea-9b01-b207170e8919.png)

VS Code is reporting following inside the Problems:
Braces should start on the same line GroovyLint(BracesForForLoop-0) 

![image](https://user-images.githubusercontent.com/45369229/85387468-2832a500-b545-11ea-9332-c040bac1ed4f.png)

If any other debug output is required feel free to notify me, I'll try to assist

**Comment by nvuillam** [comment]
This is a false positive from CodeNarc, i can't do anything about it except upgrading to CodeNarc 1.6, something I'll do one of these days ( or some other contributor if he/she's motivated :) )

For now, I advice you to disable this rule( Hover -> Quick action -> Ignore this problem for all files
