### ISSUE TITLE
 Request textDocument/codeAction failed

### ISSUE THREAD

**Issue by ahmednrana** [nvuillam/vscode-groovy-lint#6]
I am getting random errors while running command 

`GroovyLint: Analyze Code`

 ```
Message: Request textDocument/codeAction failed with message: Cannot read property 'split' of undefined
  Code: -32603 
```

**Comment by nvuillam** [comment]
I'm currently building test classes, so the extension may not be perfectly stable for now, sorry for that ^^

Please can you send me information to reproduce the problem ?

**Comment by ahmednrana** [comment]
It's random and I am now unable to reproduce it today. You may close the issue

**Comment by nvuillam** [comment]
I released a new version yesterday, it probably solved the issue you detected :)
Thanks for your feedback, do not hesitate to post new issues if you see any problem :)

**Comment by yuvmel** [comment]
Hi, I'm getting this persistently with 0.6.3 on MacOS 10.15.4, NodeJS v12.16.1 and OpenJDK 11.0.6:

> Message: Request textDocument/codeAction failed with message: Cannot read property 'split' of undefined
>   Code: -32603 

I'm also getting an "Unable to start CodeNarc Server" error right when it starts linting - is this related or should I open another issue? Thanks for publishing this promising extension!
