### ISSUE TITLE
How to see only important Problems?

### ISSUE THREAD

**Issue by pkruk2** [nvuillam/vscode-groovy-lint#60]
Hi,

by default a lot of Problems are reported, many of them are not very important (e.g. line too long, semicolons at end of line not needed, code can be rewritten etc), while others are much more interesting (e.g. variable not used).

Is there a way simply enable only "important" issues? I don't want to go over each reported problem and disable it, would be nice if I could set 1 setting or something...

**Comment by nvuillam** [comment]
1. Format your file (right click -> format), you'll see lots of errors
disappear

2. For the remaining ones:
With QuickAction you can "ignore for all project" the errors you don't want
to see (2 clicks ^^)

3. You see only "more important errors" :)

**Comment by nvuillam** [comment]
You have option groovyLint.basic.loglevel that you can use :)

![image](https://user-images.githubusercontent.com/17500430/86528861-594b9780-beac-11ea-8159-ad5ecb3a6e4b.png)

![image](https://user-images.githubusercontent.com/17500430/86528840-273a3580-beac-11ea-8202-0f1b2c61c194.png)
