### ISSUE TITLE
Wrong token and lint

### ISSUE THREAD

**Issue by baruchiro** [nvuillam/vscode-groovy-lint#61]
(Please update the title, I don't know how to call this case)

![image](https://user-images.githubusercontent.com/17686879/86526242-4d56da00-be9a-11ea-98b3-5577a6a5ccc0.png)

**Comment by nvuillam** [comment]
This is a CodeNarc false positive :)
Maybe it has been corrected in CodeNarc 1.6 ( npm-groovy-lint uses 1.5, migration has not been performed yet)
Meanwhile ... QuickAction -> ignore problem for this line :)
