### ISSUE TITLE
Is there any way to configure rules using existing codenarc.xml file?

### ISSUE THREAD

**Issue by srowan** [nvuillam/vscode-groovy-lint#68]
I already have a codenarc.xml file driving my linting rules.  Can I configure this plugin to use it so I don't need to duplicate my rule setup?

**Comment by nvuillam** [comment]
You can use ruleset file with npm-groovy-lint (ex: `npm-groovy-lint --ruleset "./config/codenarc/RuleSet-Custom.xml"`), but I've not implemented a setting for VsCode Groovy Lint

Maybe you could convert your RuleSet XML file into a .groovylintrc.js file, and it will be used in both npm-groovy-lint and VsCode GroovyLint ?

Or maybe you use this XML for another tool... if yes, which one ? I may implement the VsCode Groovy Lint setting ( or you can even do it with a PR), but only if it's really necessary :)

**Comment by srowan** [comment]
Sorry, I should have left more context!    I'm currently using gradle with the `ru.vyarus.quality` plugin.   Is there perhaps another gradle plugin that can leverage npm-groovy-lint?  (I believe `ru.vyarus.quality` calls codenarc directly).

Overall my desire is to get both VSCode highlighting as well as build lint verification (via gradle) based on the same rules definitions :)

**Comment by nvuillam** [comment]
@srowan  now you can use the same codenarc rulesets (xml / groovy) in npm-groovy-lint and Gradle CodeNarc plugins ^^

https://github.com/nvuillam/npm-groovy-lint#format

Warning: `groovylint-disable` comments are ignored by CodeNarc ^^
