### ISSUE TITLE
Ignore files/folders or set a base path for inspection

### ISSUE THREAD

**Issue by srowan** [nvuillam/vscode-groovy-lint#69]
It would be great if we could specify either
* The base folder for lint inspection (possibly passed to npm-groovy-lint via --path)
* Files/folders to exclude (possibly passed to npm-groovy-lint via --ignorepattern)

Use case: 

/src/ ... groovy src code
/test/ ... tests

My tests are spock tests, and spock has a lot of conventions which are weird / different than what you'd want for source code, so they light up like a christmas tree :)

Thanks for the great extension.

**Comment by nvuillam** [comment]
Base folder: VsCode Groovy Lint lints only the currently edited file, so... i don't see how we could define a "base folder" in settings without being a mess :)

Abou spock files, maybe you would like to use a different .groovylintrc.js file just for them ? 
What if I implement a way to add some comment at the top of the file like:
`// groovylint-use .groovylintrc.spock.js ` ?

But you would still need one call for classic groovy files and another for spock files in your gradle commands, would it be ok ?

**Comment by srowan** [comment]
Ah, yes I see.  I tend to have many files open when working on a project, so I was under the impression it was linting every file in the workspace.   

I think I found an even better way that works really well for me:  I just have one .groovylintrc.json inside `/src` and a separate groovylintrc.json inside `/test`.  And that seems to just work out of the box! 👍

**Comment by nvuillam** [comment]
Great :)
