### ISSUE TITLE
How to disable tab-to-space automatic conversion

### ISSUE THREAD

**Issue by gchianes** [nvuillam/vscode-groovy-lint#73]
The first time I got the prompt (paraphrasing) 'codenarc prefers to convert tabs to space' with options 'always', 'yes', 'no'..., I inadvertently clicked always instead of yes.  

Every time I open a groovy file, it is automatically converting tabs-to-spaces, which I will do on a branch just to reformat the source code.  In the meantime, it's causing confusion on diffs.  

I can't find a setting to disable this feature except to disable Groovy Lint completely, which I don't want to do.  Is there way to remove the saved answer 'always' on this setting?

**Comment by nvuillam** [comment]
You can just restart VsCode, as the "always" is stored in a session variable, not a VsCode setting :) 

But I strongly advise you to use "always", the first time it may generate you a big diff, but u'll be ok in the future ;)

**Comment by gchianes** [comment]
Thanks for the quick response. And very nice job on the add-on too! 

FWIW In our team environment, we try not to introduce formatting changes along with logic changes as it becomes harder to review the logic changes and increases the chances for merge issues.  We plan to use these tools to reformat the code base in a separate commit.

**Comment by nvuillam** [comment]
Glad it can help your team :)
What are you working on ?

About general formatting, I agree with you than a single commit/PR for initialization is a good idea :)

**Comment by gchianes** [comment]
We're writing CICD modules in Jenkins as the orchestration layer.  The development teams just need to update parameters in a text file in their repo, and our software reads those params and builds/deploys to AWS, Azure, App Center, etc.
