### ISSUE TITLE
Extension issues when the Windows UserName has spaces.

### ISSUE THREAD

**Issue by ariel-lenis** [nvuillam/vscode-groovy-lint#77]
Currently my Windows UserName is "Ariel Lenis" (with an space) and looks like the extension is not able to work with this scenario:

![image](https://user-images.githubusercontent.com/27330468/91478448-e20fff80-e86d-11ea-8f5b-9f882e21f223.png)

**Comment by nvuillam** [comment]
I'll have a look asap :)

**Comment by nvuillam** [comment]
A fix has been published in patch v1.2.3, please reopen if you still see the problem :)
