### ISSUE TITLE
bug on string correction

### ISSUE THREAD

**Issue by gillesnoyer** [nvuillam/vscode-groovy-lint#85]
Hi 
I have two issues on indenting the grrovy code: 
before indent: 
   pipeline.bat(
                       """pushd ${logRoot}
              if not exist ${logFolder} mkdir ${logFolder}
                 echo ${datePart} ${timePart} ${entry.key} >> ${logFolder}\\${logFile}""")

After indent :       'pushd ${logRoot}
              if not exist ${logFolder} mkdir ${logFolder}
                 echo ${datePart} ${timePart} ${entry.key} >> ${logFolder}\\${logFile}')

in this case, as there are varibale into the string, the " sould not be replaced by '

**Comment by nvuillam** [comment]
Please could you post the entire file (or a significant part of it) allowing to reproduce the issue ? Thanks !

**Comment by nvuillam** [comment]
No response for more than one month, please reopen if you provide enough info to reproduce the issue :)
