### ISSUE TITLE
Clicking on Modified .groovy File in Source Control View Opens File for Diff and Then Opens File Again

### ISSUE THREAD

**Issue by justin6case** [nvuillam/vscode-groovy-lint#94]
Vscode: 1.51.0
vscode-groovy-lint: 1.3.0
Remote - SSH: 0.56.0
Local machine: Windows 10
Remote machine: Oracle Linux 7

I typically use VS Code on my Windows 10 machine and connect via ssh using the Remote - SSH plugin to a remote Linux machine for code development. I have the vscode-groovy-lint extension installed on my local Windows machine and the remote Linux machine.

When attempting to diff .groovy files in the source control view, unexpected behavior is seen. When a file a clicked or double-clicked on, the file is opened in a tab that shows the differences between the changes made to the file since it was committed in source control. Once this diff view is open, the file is opened again in another tab (not in diff mode). this typically takes 1-2 seconds, but is sometimes faster or slower.

Additionally, if I close the newly opened file and then edit the file in the diff view, the file will again be opened in a new tab. If the file is left open in it's own tab and then is edited in the diff view, focus is then shifted from the diff view to the non-diff tab. In both these cases, the file does not have to be saved, only edited. With the 'PROBLEMS' window open, it appears the file is opened or given focus when 'GrooyLint is analyzing code' appears in the 'PROBLEMS' window.

The behavior is not observed with the vscode-groovy-lint extension disabled. The behavior related to the initial clicking or double-clicking is difficult to observe when editing files locally on the Windows machine, but the remaining behavior is seen regardless of whether files are edited locally or remotely.

**Comment by DavidHulsman** [comment]
Mitigation: Change the `groovyLint.lint.trigger` option from `onType` to either `onSave` or `user` (manual trigger).
