### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Augusto-s-t** [nvuillam/vscode-groovy-lint#99]
- Issue Type: `Performance`
- Extension Name: `vscode-groovy-lint`
- Extension Version: `1.4.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\augus\AppData\Local\Temp\NicolasVuillamy.vscode-groovy-lint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nvuillam** [comment]
Please could you attach the file to this issue ?

About npm-groovy-lint performances (VsCode Groovy Lint uses npm-groovy-lint) ... it's unfortunately a known problem, as [CodeNarc](https://github.com/CodeNarc/CodeNarc) (Groovy linter behind npm-groovy-lint) consumes a lot of CPU performances.

I managed a way to keep a CodeNarc server alive so JVM does not have to be launched at every lint, and it improved a lot performances... but it still consumes a lot :/

I have no idea about how (or if) I can again improve performances of CodeNarc :/
